### PR TITLE
support ArrayBuffer, TypedArray and Array of Number.

### PR DESCRIPTION
**Pull request by youkinjoh**
modify WebSocket Server supported ArrayBuffer, TypedArray and Array of Number.

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
PR #366 comments apply there. 

Great PR by the way!

**Comment by youkinjoh** [comment]
I will rewrite code after merge #366.

**Comment by beaufortfrancois** [comment]
PR #366 has been merged.

**Comment by youkinjoh** [comment]
I tried write comment.
```
    // WebSocket must specify opcode when send frame.
    // The opcode for data frame is 1(text) or 2(binary).
```
If this comment is crazy English, do you modify comment.

**Comment by beaufortfrancois** [comment]
Thanks You so much!
I've bumped manifest version and updated webstore item at https://chrome.google.com/webstore/detail/websocket-server-test/pkbpddppnkjmlbgliipgmhjeialadokj

**Comment by youkinjoh** [comment]
I found missing link in Chrome Web Store.

place "作成者: Chrome App Samples" by Japanese.
current link -> https://github.com/GoogleChrome/chrome-app-samples/tree/master/websocket-server
correct link? -> https://github.com/GoogleChrome/chrome-app-samples/tree/master/samples/websocket-server
----
**screenshot**

----
**forcus link**

**Comment by beaufortfrancois** [comment]
Just fixed it. Thanks!

**Pull request merged**
