### PR TITLE
Fix typo in logging of runtime error

### PR DESCRIPTION
**Pull request by davidrs**
This typo will cause it's own error if hit :)

### CODE REVIEW

**Comment by davidrs** [comment]
I signed it!

**Comment by davidrs** [comment]
I signed it!

**Comment by beaufortfrancois** [comment]
Thank you!
Please make sure the email address you used is the same as GitHub one.

**Comment by davidrs** [comment]
I don't think I had my email address set on the commits. Do I need to redo the commits and PR with the email address set?

**Comment by beaufortfrancois** [comment]
If that's ok with you, I will apply patch myself so that you don't have to redo the commit. If not, I'll wait.

**Comment by davidrs** [comment]
@beaufortfrancois  That would be wonderful, thanks.

**Comment by beaufortfrancois** [comment]
Applied in https://github.com/GoogleChrome/chrome-app-samples/commit/dd0564680458d43b3128efb8c622d1f2ddb7b909
Thank you again David!

**Pull request closed without merging**
