### PR TITLE
[webview browser] Add a dialog for clearing data

### PR DESCRIPTION
**Pull request by oahziur**
This fixes https://code.google.com/p/chromium/issues/detail?id=520171.

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Thank you!
Can you remove trailing whitespaces? And I'll merge this PR.

**Comment by oahziur** [comment]
I have cleaned up whitespaces.  PTAL. Thanks!

**Comment by beaufortfrancois** [comment]
Perfect! I'll bump app manifest version.

**Comment by beaufortfrancois** [comment]
https://chrome.google.com/webstore/detail/edggnmnajhcbhlnpjnogkjpghaikidaa has been updated.

**Pull request merged**
