### PR TITLE
support utf-8.

### PR DESCRIPTION
**Pull request by youkinjoh**
modify WebSocket Server supported utf-8.

### CODE REVIEW

**Comment by beaufortfrancois** [comment]
Thank You Kinjoh!
Let me have a look and I'll get back to you shortly.

**Comment by youkinjoh** [comment]
```js
try {
  var server = new http.Server();
  var wsServer = new http.WebSocketServer(server);
  server.listen(9999);
  wsServer.addEventListener('request', function(req){
    var socket = req.accept();
    socket.addEventListener('message', function(e) {
      console.log('server');
      console.log(e.data); // => (A)
      socket.send(e.data);
    });
    return true;
  });
} catch(e) {
  console.log(e);
}

setTimeout(function() {
  var ws = new WebSocket('ws://localhost:9999');
  ws.addEventListener('open', function() {
    ws.send('あいうえお');
  });
  ws.addEventListener('message', function(e) {
    console.log('client');
    console.log(e.data); // => (B)
  });
}, 1000);
```

# result

## commit id d9615fb6d182c3cc1f794a29324791f96843287d

(A) `ããããã`
(B) `あいうえお`

## commit id 59095f9e4a3eb339cc4dcc6502a0ad63d85e16b6

(A) `あいうえお`
(B) `あいうえお`

**Comment by beaufortfrancois** [comment]
I'm having some issues running this app on Chrome OS and Mac OS.
Which chrome version and platform do you use?

**Comment by youkinjoh** [comment]
I use Mac OS X 10.9(Mavericks).

**Comment by beaufortfrancois** [comment]
OK. I see now what wasn't working for me... and it has nothing to do with your amazing patch by the way. 

I'll merge this PR as soon as you confirm you've signed the CLA. As you may know, _we require contributors to sign Google's open source Contributor License Agreement. Individuals can sign electronically in seconds. See https://github.com/GoogleChrome/chrome-app-samples/blob/master/CONTRIBUTING.md._

For info, WebSocket Server was not listening yet when DOMContentLoaded event was triggered which mean my web socket could not be created at that time. I understand now why your example had a setTimeout in it... 
Do you think we could update `http.Server listen()` to return a callback when port is actually opened?

**Comment by youkinjoh** [comment]
I will agree CLA after.

> For info, WebSocket Server was not listening yet when DOMContentLoaded event was triggered which mean my web socket could not be created at that time. I understand now why your example had a setTimeout in it... 

Sorry...
I can't use English well than Japanese.
I tried to talk in code, but it seems to have failed.

> Do you think we could update http.Server listen() to return a callback when port is actually opened?

That mean node.js style?

https://nodejs.org/api/http.html#http_server_listen_port_hostname_backlog_callback
https://nodejs.org/api/http.html#http_server_listen_path_callback
https://nodejs.org/api/http.html#http_server_listen_handle_callback

If so, I think good idea.

**Comment by youkinjoh** [comment]
I agreed CLA.

**Comment by beaufortfrancois** [comment]
I just merged your PR.
Let's continue this discussion at #368 if you don't mind.

**Pull request merged**
